### ISSUE TITLE
Cannot use the index tool jar file to reindex jsonld objects

### ISSUE THREAD

**Issue by taojing2002** [DataONEorg/d1_cn_index_tool#2]
I noticed we can't reindex jsonld objects by the jar file and there was no obvious errors. After adding more debug statement, I found the error message:
```
java.lang.NoSuchFieldError: UTF_32BE
	at com.github.jsonldjava.utils.JsonUtils.fromInputStream(JsonUtils.java:104)
	at org.apache.jena.riot.lang.JsonLDReader.read(JsonLDReader.java:76)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:257)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:243)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:70)
	at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:277)
	at org.dataone.cn.indexer.parser.JsonLdSubprocessor.processDocument(JsonLdSubprocessor.java:303)
	at org.dataone.cn.indexer.SolrIndexService.processObject(SolrIndexService.java:230)
	at org.dataone.cn.indexer.SolrIndexService.insertIntoIndex(SolrIndexService.java:303)
	at org.dataone.cn.index.processor.IndexTaskUpdateProcessor.process(IndexTaskUpdateProcessor.java:50)
	at org.dataone.cn.index.processor.IndexTaskProcessor.processTask(IndexTaskProcessor.java:288)
	at org.dataone.cn.index.processor.IndexTaskProcessor.access$000(IndexTaskProcessor.java:80)
	at org.dataone.cn.index.processor.IndexTaskProcessor$1.run(IndexTaskProcessor.java:265)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by taojing2002** [comment]
It turns out that the commons-io jar file is too old:
https://stackoverflow.com/questions/48299276/how-do-i-resolve-this-error-java-lang-nosuchfielderror-utf-32be

**Comment by taojing2002** [comment]
Now the fix was committed the develop_2.3 branch. We need to merge it to main.
